spring.application.name=epoi

spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

spring.threads.virtual.enabled=true

egov.jsm.api.client-key=${EGOV_JSM_API_KEY}

naver.map.api.client-id=${NX_NCP_APIGW_API_KEY_ID}
naver.map.api.client-key=${NX_NCP_APIGW_API_KEY}

naver.search.api.client-id=${NX_SEARCH_API_KEY_ID}
naver.search.api.client-key=${NX_SEARCH_API_KEY}

kakao.api.restapi-key=${KAKAO_AK_REST_API_KEY}
kakao.api.admin-key=${KAKAO_AK_ADMIN_KEY}